version: '3.1'

services:
  myapp:
    build: nginx/.
    container_name: myapp
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: lorensetti
      MYSQL_PASSWORD: pwd123
    ports:
      - 3306:3306
    volumes:
      - ./mysql_volume:/var/lib/mysql